#  Copyright (C) 2026 Your GitHub Username
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <https://gnu.org>.
#
#  Physical 3D outputs and CAD files generated by this script are 
#  simultaneously governed by the CERN Open Hardware License v2 - 
#  Weakly Reciprocal (CERN-OHL-W-2.0). See LICENSE_HARDWARE for details.

"""
Core Visualization Engine for the TA-MHD Vortex Engine.
Calculates and updates coupled fluid, magnetic, and acoustic matrices.
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Slider, Button
from config import ENGINE_DIMENSIONS, FLUID_PRESETS, ACTIVE_FLUID

class TAMHDEngine:
    def __init__(self, grid_size=40):
        self.grid_size = grid_size
        
        # Pull configurations cleanly from config.py
        self.fluid_props = FLUID_PRESETS[ACTIVE_FLUID]
        self.density = self.fluid_props["density"]
        self.conductivity = self.fluid_props["conductivity"]
        
        # Establish chamber bounds using metric equivalents
        bound = ENGINE_DIMENSIONS["outer_radius_mm"] / 38.1 # Standardized scale for grid plotting
        x = np.linspace(-bound, bound, grid_size)
        y = np.linspace(-bound, bound, grid_size)
        
        self.X, self.Y = np.meshgrid(x, y)
        self.R = np.sqrt(self.X**2 + self.Y**2) + 1e-5 # Avoid division by zero
        self.time = 0.0
        
    def compute_physics_step(self, b_strength, ac_freq, dt):
        """
        Solves the coupled Maxwell-Navier-Stokes-Acoustic equations.
        """
        self.time += dt
        omega = 2 * np.pi * ac_freq
        
        # 1. MAGNETICS: Superposition of Counter-Rotating Fields
        theta_1 = omega * self.time
        theta_2 = -omega * self.time
        
        B1_x, B1_y = b_strength * np.cos(theta_1), b_strength * np.sin(theta_1)
        B2_x, B2_y = b_strength * np.cos(theta_2), b_strength * np.sin(theta_2)
        
        Bx_net = B1_x + B2_x
        By_net = B1_y + B2_y
        
        # 2. ACOUSTICS: Pressure Density Fluctuations
        acoustic_wave = np.sin(2 * np.pi * (self.R - 5 * self.time))
        current_density = self.conductivity * acoustic_wave * 0.01
        
        # 3. MHD/FLUID: Lorentz Force Driving the Vortex (F = J x B)
        force_x = -current_density * By_net
        force_y = current_density * Bx_net
        
        # Calculate resulting velocity vectors relative to material density
        vel_x = (force_x / self.density) * self.Y / self.R
        vel_y = (-force_y / self.density) * self.X / self.R
        
        # 4. THERMODYNAMICS: Viscous Dissipation Friction
        velocity_magnitude = np.sqrt(vel_x**2 + vel_y**2)
        thermal_energy = 0.5 * self.density * (velocity_magnitude**2)
        
        return vel_x, vel_y, acoustic_wave, thermal_energy, Bx_net, By_net

def run_digital_twin():
    engine = TAMHDEngine()
    dt = 0.01
    init_b = 1.5   # Tesla
    init_hz = 60.0 # Hz
    
    fig, axs = plt.subplots(1, 2, figsize=(14, 6))
    plt.subplots_adjust(bottom=0.25)
    
    vx, vy, press, therm, bx, by = engine.compute_physics_step(init_b, init_hz, 0)
    
    im_press = axs[0].imshow(press, extent=[-2, 2, -2, 2], cmap='coolwarm', origin='lower', vmin=-1, vmax=1)
    quiver_vortex = axs[0].quiver(engine.X, engine.Y, vx, vy, color='black', alpha=0.6, scale=0.5)
    axs[0].set_title(f"Acoustic Density & Vortex Vectors\nMedium: {engine.fluid_props['name']}")
    fig.colorbar(im_press, ax=axs[0], label="Relative Density Delta")
    
    im_therm = axs[1].imshow(therm, extent=[-2, 2, -2, 2], cmap='inferno', origin='lower')
    axs[1].set_title("Thermal Energy Density (Shearing Friction)")
    fig.colorbar(im_therm, ax=axs[1], label="Joules / m^3")
    
    ax_b = plt.axes([0.15, 0.13, 0.65, 0.03])
    ax_hz = plt.axes([0.15, 0.08, 0.65, 0.03])
    
    slider_b = Slider(ax_b, 'Magnetic Field (Tesla)', 0.1, 5.0, valinit=init_b, valstep=0.1)
    slider_hz = Slider(ax_hz, 'Acoustic Freq (Hz)', 10.0, 500.0, valinit=init_hz, valstep=5.0)
    
    def update(val):
        vx_new, vy_new, press_new, therm_new, bx_n, by_n = engine.compute_physics_step(slider_b.val, slider_hz.val, dt)
        im_press.set_data(press_new)
        im_therm.set_data(therm_new)
        im_therm.set_clim(vmin=therm_new.min(), vmax=therm_new.max())
        quiver_vortex.set_UVC(vx_new, vy_new)
        fig.canvas.draw_idle()
        
    slider_b.on_changed(update)
    slider_hz.on_changed(update)
    
    ax_step = plt.axes([0.82, 0.02, 0.1, 0.04])
    btn_step = Button(ax_step, 'Time Step Forward', color='lightgray', hovercolor='0.97')
    btn_step.on_clicked(update)
    
    plt.show()

if __name__ == "__main__":
    run_digital_twin()
        
